# Marketing Mix Modelling 

in this project, I analyse marketing spends data and try to understand its relationship with sales for that calendar week. Using insights from said analyses, I will build a forecasting model

## Data Loading and prerequisites

In [40]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [41]:
df = pd.read_csv('../data/Raw/Sample Media Spend Data.csv')

In [42]:
df.head()

,Division,Calendar_Week,Paid_Views,Organic_Views,Google_Impressions,Email_Impressions,Facebook_Impressions,Affiliate_Impressions,Overall_Views,Sales
0,A,1/6/2018,392,422,408,349895.0107,73580,12072,682,59417
1,A,1/13/2018,787,904,110,506270.2176,11804,9499,853,56806
2,A,1/20/2018,81,970,742,430042.1538,52232,17048,759,48715
3,A,1/27/2018,25,575,65,417745.6658,78640,10207,942,72047
4,A,2/3/2018,565,284,295,408505.8012,40561,5834,658,56235

In [43]:
df.tail()

,Division,Calendar_Week,Paid_Views,Organic_Views,Google_Impressions,Email_Impressions,Facebook_Impressions,Affiliate_Impressions,Overall_Views,Sales
3046,Z,2/1/2020,29239,25311,622406,1.459071e+06,45026,12098,53667,82707
3047,Z,2/8/2020,26230,28031,624409,5.342505e+05,227070,9548,53665,84503
3048,Z,2/15/2020,24749,31281,439362,4.227182e+05,393685,9861,55561,147325
3049,Z,2/22/2020,20713,30356,464178,6.085799e+05,424676,10221,49221,111525
3050,Z,2/29/2020,15990,26993,449032,4.390165e+05,161439,10294,42994,98187

In [44]:
df.shape

(3051, 10)

In [45]:
df.columns

Index(['Division', 'Calendar_Week', 'Paid_Views', 'Organic_Views',
       'Google_Impressions', 'Email_Impressions', 'Facebook_Impressions',
       'Affiliate_Impressions', 'Overall_Views', 'Sales'],
      dtype='str')

In [46]:
df.dtypes

Division                     str
Calendar_Week                str
Paid_Views                 int64
Organic_Views              int64
Google_Impressions         int64
Email_Impressions        float64
Facebook_Impressions       int64
Affiliate_Impressions      int64
Overall_Views              int64
Sales                      int64
dtype: object

In [47]:
df.columns = map(str.lower, df.columns)

In [48]:
df.columns

Index(['division', 'calendar_week', 'paid_views', 'organic_views',
       'google_impressions', 'email_impressions', 'facebook_impressions',
       'affiliate_impressions', 'overall_views', 'sales'],
      dtype='str')

### Variable Identification and Typecasting

In [49]:
df.dtypes

division                     str
calendar_week                str
paid_views                 int64
organic_views              int64
google_impressions         int64
email_impressions        float64
facebook_impressions       int64
affiliate_impressions      int64
overall_views              int64
sales                      int64
dtype: object

calendar_week is here as a string, but will be converted to date time

In [50]:
#identify variables with integer datatype 
df.dtypes[df.dtypes == 'int64']

paid_views               int64
organic_views            int64
google_impressions       int64
facebook_impressions     int64
affiliate_impressions    int64
overall_views            int64
sales                    int64
dtype: object

Summary: 
* paid_views and organic views, these represent the amount of youtube paid and organic views, remains an integer 
* Google impressions, facebook impressions, affiliate impressions: these account for the number of impressions gained by various channels, hence will remain an integer
* Overall_views accounts for the total amount of views from all channels, remains an integer 
* Sales: Total amount of sales gotten, remains an integer

In [51]:
#Identifying variables with float datatype 
df.dtypes[df.dtypes == 'float64']

email_impressions    float64
dtype: object

Summary: 
* email_impressions: These are the amount of impressions gotten via email, will be converted to an integer

In [52]:
df['email_impressions'].isna().value_counts()

email_impressions
False    3051
Name: count, dtype: int64

In [53]:
df['email_impressions']

0       3.498950e+05
1       5.062702e+05
2       4.300422e+05
3       4.177457e+05
4       4.085058e+05
            ...
3046    1.459071e+06
3047    5.342505e+05
3048    4.227182e+05
3049    6.085799e+05
3050    4.390165e+05
Name: email_impressions, Length: 3051, dtype: float64

In [58]:
df['email_impressions'] = np.round(df['email_impressions'], decimals = 1)
df['email_impressions'] = df['email_impressions'].astype(int)

In [62]:
#Identifying variables with str datatype
df.dtypes[df.dtypes == 'str']

division         str
calendar_week    str
dtype: object

Summary: 
* division: Alphabetical delineation between company divisions, remains as string 
* calendar_week: represents the first day of the week, will be converted to datetime

In [67]:
df['calendar_week'] = pd.to_datetime(df['calendar_week'])

In [68]:
df['calendar_week'].dtype

dtype('<M8[us]')

In [70]:
df.head()

,division,calendar_week,paid_views,organic_views,google_impressions,email_impressions,facebook_impressions,affiliate_impressions,overall_views,sales
0,A,2018-01-06,392,422,408,349895,73580,12072,682,59417
1,A,2018-01-13,787,904,110,506270,11804,9499,853,56806
2,A,2018-01-20,81,970,742,430042,52232,17048,759,48715
3,A,2018-01-27,25,575,65,417745,78640,10207,942,72047
4,A,2018-02-03,565,284,295,408505,40561,5834,658,56235